# Generated by Django 4.2.7 on 2023-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unwantedhit',
            name='success',
        ),
        migrations.AddField(
            model_name='unwantedhit',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
