# Generated by Django 4.2.7 on 2023-11-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0002_remove_unwantedhit_success_unwantedhit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='unwantedhit',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
    ]
